# frozen_string_literal: true

source 'https://rubygems.org'

gem 'yardcheck', path: '..'
gem 'pry', git: 'https://github.com/mvz/pry.git', branch: 'strip-readline-prompt-ignore-codes'
gem 'pry-byebug'
